apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_HOST
              value: {{ .Values.env.mysqlhost }}
            - name: MYSQL_USER
              value: {{ .Values.env.mysqluser }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.env.mysqlpassword }}
            - name: MYSQL_DB
              value: {{ .Values.env.mysqldb }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetport }}
